### PR TITLE
fix: replace assert syntax to be forwards compatible

### PR DESCRIPTION
**Pull request by mrstork**
https://linear.app/netlify/issue/CPLA-2678

### CODE REVIEW

File: src/__csp-nonce.ts [hunk 1]
```diff
@@ -1,10 +1,12 @@
 /* eslint-disable */
 // @ts-ignore
+import { readFile } from 'node:fs/promises'
+// @ts-ignore
 import type { Config, Context } from "netlify:edge";
 // @ts-ignore
 import { csp } from "https://deno.land/x/csp_nonce_html_transformer@v2.2.2/src/index-embedded-wasm.ts";
 // @ts-ignore
-import inputs from "./__csp-nonce-inputs.json" assert { type: "json" };
+const inputs = await readFile(new URL('./__csp-nonce-inputs.json', import.meta.url), 'utf-8')
```
Comment (JakeChampion) [inline src/__csp-nonce.ts:9]: I don't think edge functions have the fs apis available to use unfortunately

File: src/__csp-nonce.ts [hunk 2]
```diff
@@ -3,8 +3,7 @@
 import type { Config, Context } from "netlify:edge";
 // @ts-ignore
 import { csp } from "https://deno.land/x/csp_nonce_html_transformer@v2.2.2/src/index-embedded-wasm.ts";
-// @ts-ignore
-import inputs from "./__csp-nonce-inputs.json" assert { type: "json" };
+import inputs from "./__csp-nonce-inputs.json";
```
Comment (mrstork) [inline src/__csp-nonce.ts:6]: For reference, this yields:
```
src/__csp-nonce.ts(6,20): error TS2732: Cannot find module './__csp-nonce-inputs.json'. Consider using '--resolveJsonModule' to import module with '.json' extension.
```

File: src/__csp-nonce.ts [hunk 3]
```diff
@@ -4,7 +4,7 @@ import type { Config, Context } from "netlify:edge";
 // @ts-ignore
 import { csp } from "https://deno.land/x/csp_nonce_html_transformer@v2.2.2/src/index-embedded-wasm.ts";
 // @ts-ignore
-import inputs from "./__csp-nonce-inputs.json" assert { type: "json" };
+import inputs from "./__csp-nonce-inputs.json" with { type: "json" };
```
Comment (mrstork) [inline src/__csp-nonce.ts:7]: For reference, fails with syntax errors:
```
src/__csp-nonce.ts(7,48): error TS1005: ';' expected.
src/__csp-nonce.ts(7,53): error TS1005: '(' expected.
src/__csp-nonce.ts(7,69): error TS1005: ')' expected.
```

File: src/__csp-nonce.ts [hunk 4]
```diff
@@ -3,8 +3,12 @@
 import type { Config, Context } from "netlify:edge";
 // @ts-ignore
 import { csp } from "https://deno.land/x/csp_nonce_html_transformer@v2.2.2/src/index-embedded-wasm.ts";
-// @ts-ignore
-import inputs from "./__csp-nonce-inputs.json" assert { type: "json" };
+
+// @ts-ignore top-level await
+const { default: inputs } = await import("./__csp-nonce-inputs.json", {
+  // @ts-ignore 'with' syntax
+  with: { type: "json" },
```
Comment (mrstork) [inline src/__csp-nonce.ts:10]: Using `with` directly fails due to the node 18 type-checking we're doing on this file, but works fine in deno `1.46.3` and `2.x` which is what the functions are bundled and run with

Comment (mrstork) [reply src/__csp-nonce.ts:9]: Yes, we could fix up typechecking in the repository so that it respects deno syntax, but I think that work should be done in another PR

**Review by ndhoule — APPROVED** [review]
